# Phase 1 – NumPy Fundamentals

## Notes
- NumPy is a fast numerical computing library.
- Arrays are faster and more memory efficient than Python lists.
- Arrays can be 1D, 2D, or higher dimensional.


In [1]:
import numpy as np

## 1. Creating Arrays

In [2]:
arr_1d = np.array([1,2,3,4,5])
arr_2d = np.array([[1,2,3],[4,5,6]])

print(arr_1d)
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Explanation
- `np.array()` converts Python lists into NumPy arrays.

## 2. Python List vs NumPy Array

In [3]:
py_list=[1,2,3]
np_array=np.array([1,2,3])

print(py_list*2)      # repeats list
print(np_array*2)     # element-wise multiplication

[1, 2, 3, 1, 2, 3]
[2 4 6]


## 3. Creating Arrays from Scratch

In [4]:
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.full((2,2),7))
print(np.arange(0,10,2))
print(np.random.random((2,2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[0 2 4 6 8]
[[0.62855037 0.40636975]
 [0.70612604 0.40327224]]


## 4. Vector, Matrix, Tensor

In [5]:
vector=np.array([1,2,3])
matrix=np.array([[1,2],[3,4]])
tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(vector)
print(matrix)
print(tensor)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 5. Array Properties

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Dimensions:",arr.ndim)
print("Size:",arr.size)
print("Data Type:",arr.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


## 6. Reshaping

In [7]:
arr=np.arange(12)
print(arr.reshape(3,4))
print(arr.flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


## Key Takeaways
- Prefer NumPy for numerical work.
- Learn shape, ndim, size and reshape well.